[username]
format = " [â•­â”€$user]($style)@"
show_always = true
style_root = "bold red"
style_user = "bold red"

# Second param
[hostname]
disabled = false
format = "[$hostname]($style) "
ssh_only = false
style = "bold dimmed red"
trim_at = "-"

[directory]
disabled = true

# Last param in the first line/row
[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 2_000

# Prompt: param 2
[character]
error_symbol = " [Ã—](bold red)"
success_symbol = " [â•°â”€Î»](bold red)"

# SYMBOLS
[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "ğŸ”´"

[aws]
symbol = "îŒ½ "
format = "[ $symbol$version ]($style)"

[conda]
symbol = "ï„Œ "
format = "[ $symbol$version ]($style)"

[dart]
symbol = "î˜ "
format = "[ $symbol$version ]($style)"

[docker_context]
symbol = "ïŒˆ "
format = "[ $symbol$version ]($style)"

[elixir]
symbol = "î‰µ "
format = "[ $symbol$version ]($style)"

[elm]
symbol = "î˜¬ "
format = "[ $symbol$version ]($style)"

[package]
disabled = true
symbol = " ó°— "

[git_branch]
symbol = "ï˜ "
format = ' [$symbol$branch(:$remote_branch)]($style) '

[git_status]
disabled = true

[golang]
symbol = "î˜§ "
format = "[ $symbol$version ]($style)"

[hg_branch]
symbol = "ï˜ "
format = "[ $symbol$version ]($style)"

[java]
symbol = "î‰– "
format = "[ $symbol$version ]($style)"

[julia]
symbol = "î˜¤ "
format = "[ $symbol$version ]($style)"

[nim]
symbol = "ïš¤ "
format = "[ $symbol$version ]($style)"

[nix_shell]
symbol = "ï‹œ "
format = "[ $symbol$version ]($style)"

[nodejs]
symbol = " î´ "
format = "[ $symbol$version ]($style)"

[perl]
symbol = "î© "
format = "[ $symbol$version ]($style)"

[php]
symbol = "î˜ˆ "
format = "[ $symbol$version ]($style)"

[python]
symbol = "î˜† "
format = "[ $symbol$version ]($style)"

[ruby]
symbol = "îˆ¾ "
format = "[ $symbol$version ]($style)"

[rust]
symbol = "î¨ "
format = "[ $symbol$version ]($style)"

[swift]
symbol = "ï¯£ "
format = "[ $symbol$version ]($style)"
